name: Terraform Continue Integration

on:
  push:
    branches:
    - 'az-devops'

jobs:    
  Virtual-network:
    name: "Deploy Virtual Network module"
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: modules/virtual_network
    steps:

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: 025881d1-4538-4bee-8194-b1d89351603e
        tenant-id: bc877e61-f6cf-4461-accd-0565fa4ca357
        subscription-id: ec0ba952-4ae9-4f69-b61c-4b96ff470038

    - name: 'Run az commands'
      run: |
        az account show
        az group list
        pwd 

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init
        
